commit nested destroy patient, clinical_reference and counter_reference
TauroAlde/Sesa pull request #3
Opened 2017-05-04 16:48 UTC by TauroAlde

nested destroy patient, clinical_reference and counter_reference

2017-05-04 16:58 UTC, alexisraca requested changes

2017-05-04 16:58 UTC, alexisraca commented on app/admin/clinical_counter_reference.rb
> +        clinical_counter_reference.diagnostics.each do |diagnostic|
Esto se puede refactorar con .map https://ruby-doc.org/core-2.2.0/Array.html#method-i-map

2017-05-08 16:19 UTC, alexisraca commented on app/admin/clinical_counter_reference.rb
> +        clinical_counter_reference.diagnostics.map{|diagnostics|diagnostics.name}.join(", ")
Como buena practica, Hay que poner espacios entre los elementos del codigo para mejor interpretación:

.map{ |diagnostics| diagnostics.name }  es mas facil de leer que vv
.map{|diagnostics|diagnostics.name}

2017-05-08 16:27 UTC, TauroAlde commented on app/admin/clinical_counter_reference.rb
> +        clinical_counter_reference.diagnostics.map{|diagnostics|diagnostics.name}.join(", ")
haaa ok ok

2017-05-08 16:34 UTC, TauroAlde commented on app/admin/clinical_counter_reference.rb
> +        clinical_counter_reference.diagnostics.map{|diagnostics|diagnostics.name}.join(", ")
ya quedo ya lo pushe

2017-05-08 16:42 UTC, alexisraca commented on app/admin/clinical_counter_reference.rb
> +        clinical_counter_reference.diagnostics.map{ |diagnostics| diagnostics.name }.join(", ")
.diagnostics.map{ |diagnostics| diagnostics.name }

cambia la variable del bloque a singular, cuando haces .diagnostics.map se supone que dentro del map iteras diagnostico por diagnostico entonces gramaticalmente debes tenerlo en singular dentro del bloque.

map { |diagnostic| diagnostic.name }

Tambien pon un espacio entre el "map" y el inicio del bloque "{"

hay una forma mas corta de hacer un bloque map si vas a correr un solo metodo para todos los elementos:

.map(&:name)   en lugar de  .map{ |diagnostics| diagnostics.name }   (SOLO FUNCIONA CUANDO CORRES UN SOLO METODO SOBRE CADA ELEMENTO)

2017-05-08 18:00 UTC, merged